### ISSUE TITLE
Cannot download test data

### ISSUE THREAD

**Issue by LiberiFatali** [VisionLearningGroup/visda-2019-public#2]
I got 404 Not Found: The requested URL /ftp/visda/2019/semi-supervised/clipart.zip was not found on this server.

**Comment by ksaito-ut** [comment]
Sorry for the inconvenience. We've fixed the issue.

**Comment by andriiD** [comment]
Some images are missing, for example "0uBsmw7n1egU.jpg" in "clipart_unl.txt" is not found in the clipart_visda

**Comment by layumi** [comment]
Hi @ksaito-ut 
I also find that some images are missing in `clipart_visda`, e.g., the first image named `XmpS39Bw7Uwp.jpg` in `clipart_labeled.txt`.

**Comment by ksaito-ut** [comment]
@layumi @andriiD 
Hi, wrong zip was placed in the folder. I've fixed the issue. Sorry for the inconvenience. 
The corresponding submission_list file is "all_list_public.txt" file. This is different from the submission file of multi-source adaptation.
