### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Execution time limit exceeded!

### ISSUE THREAD

**Issue by layumi** [VisionLearningGroup/visda-2019-public#4]
When I submit my test result, I face an issue in CodaLab  as follows: 
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Execution time limit exceeded!
```
I am not sure whether it is cased by my submission file. 
In my submission file, there are 122522 lines. Every line is a class number.

**Comment by andriiD** [comment]
I had the same issue, it fails randomly. Try to submit your file again, it should work

**Comment by layumi** [comment]
Thanks a lot @andriiD

**Comment by filaPro** [comment]
Same problem for me! Also want to know if this failed submissions count from total 20 submissions limit.

**Comment by denemmy** [comment]
I had the same issue.

**Comment by feinanshan** [comment]
Hi, 
Only the successfully evaluated submissions will be counted. The WARNING is due to the allocation of computation resource in the Codalab server. 
Please ignore this and resubmit the results if it fails for this reason.

**Comment by surajiiitd** [comment]
I tried 5 times. But it did not work in my case. 


It is giving the same warning all the times.
I have to fix this asap (Organizer side)

**Comment by somaia02** [comment]
I solved the problem by compressing the files not the folder that contains them
