### ISSUE TITLE
'MME + ResNet34' on 'R to S' is about 46% (semi-supervised)

### ISSUE THREAD

**Issue by canqin001** [VisionLearningGroup/visda-2019-public#6]
Hi, I just run the code of SSDA. But the performance on R to S is about 46% which is far below the results in paper. Do you have any suggestions?

**Comment by ksaito-ut** [comment]
Did you run the experiments using all classes in the dataset? 
I guess you ran the code using 345 classes. In SSDA paper, we picked up 125 classes, which can make a large difference.

**Comment by canqin001** [comment]
I see. But I have noticed there is only option for args.dataset which is 'multi_all'. How to run the code with 125 classes?

**Comment by ksaito-ut** [comment]
If you want to run with 125 classes, please use the list here https://github.com/VisionLearningGroup/SSDA_MME/tree/master/data/txt/multi .
I published the code of MME and image lists used to run the experiments.

**Comment by canqin001** [comment]
All right. Thanks a lot :)
